### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by chikamichi** [UJKhokhar/blocitoff-api#2]
Here are a few guidelines to get you started. Details below the checklist.

---

The simplest way to implement the API for Blocitoff is to build it within the current app, using a dedicated "namespace". It is possible to separate the API from the "regular" application itself, but it would require more work, and I'd suggest taking things slowly.

To get started, let's implement an API endpoint to retrieve the items for a specific user.

* [x] remove CSRF `:exception` strategy
* [x] create a namespace for the API controllers
* [x] create an API controller for the items
* [x] render JSON using a serializer for the items
* [x] test a GET request to fetch a user's items from the API

**Comment by chikamichi** [comment]
### Remove CSRF `:exception` strategy

See #1 for details.

**Comment by chikamichi** [comment]
#### Create a namespace for the API controllers

Currently, your app has urls such as /users/6/items. What you'd want, is something like /api/users/6/items as well, where the response wouldn't be HTML, but [JSON](https://en.wikipedia.org/wiki/JSON).

Let's start with the routes file, then. In config/routes.rb:

``` ruby
Blocitoff::Application.routes.draw do
  namespace :api do
    # Feel free to filter available actions.
    resources :user do
     resources :items
    end
  end
end
```

This will recognize the required urls. The matching controllers must be created inside a new directory, app/controllers/api/.

**Comment by chikamichi** [comment]
#### Create an API controller for the items

Let's say you'd like to implement the `show` action for `:items`, matching a url such as /api/users/6/items.

``` ruby
# app/controllers/api/items_controller.rb
class Api::ItemsController < Api::ApiController
  def show
    # …
  end
end
```

**Comment by chikamichi** [comment]
#### Render JSON using a serializer for the items

Two resources on this:

* [Bloc's resource](https://www.bloc.io/resources/serializers)
* [The official documentation](https://github.com/rails-api/active_model_serializers/tree/0-9-stable) for the latest stable version, 0.9

**Comment by chikamichi** [comment]
#### Test a GET request to fetch a user's items from the API

``` sh
curl -v http://localhost:3000/api/users/6/items
```

should return a JSON list of items for the specified user.

**Comment by UJKhokhar** [comment]
Hey. I implemented what you outlined above, but I'm running into an error. Tried to troubleshoot but stillo unsure.

First I changed the ```resources :user``` to ```resources :users``` to match the routes.

Then I ran ```rake routes``` and realized that the show action's route is ```/api/users/:user_id/items/:id(.:format)``` and we don't want just one ID so I changed the items#show to items#index to match the route ```/api/users/:user_id/items(.:format)```

Although that didn't work either. Running ```curl -v http://localhost:3000/api/users/6/items``` returns a giant stack that I'm not sure how to decipher. The server stack is returning the following: 

```
Completed 404 Not Found in 1ms

ActiveRecord::RecordNotFound (Couldn't find User with 'id'=):
  app/controllers/api/items_controller.rb:3:in `index'
```

**Comment by UJKhokhar** [comment]
Oops. I figured it out. In my items_controller, I was passing ```:id``` into ```User.find(params[ ])``` instead of ```:user_id```

**Comment by chikamichi** [comment]
Nice! I tested it, it works:

``` sh
# rails s running…
￼￼$ curl -v http://localhost:3000/api/users/6/items
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /api/users/6/items HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:3000
> Accept: */*
> 
< HTTP/1.1 200 OK 
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Type: application/json; charset=utf-8
< Etag: W/"046556ec03b7df39639c042b75c9d03c"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: d8d4d5ab-822e-4e7a-9910-c57747a9bc11
< X-Runtime: 0.010191
* Server WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26) is not blacklisted
< Server: WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26)
< Date: Wed, 25 Mar 2015 09:04:54 GMT
< Content-Length: 735
< Connection: Keep-Alive
< 
* Connection #0 to host localhost left intact
{"items":[{"id":2,"name":"Nesciunt alias doloribus non.","created_at":"2015-03-25T09:02:55.641Z"},{"id":4,"name":"Rerum perferendis repellendus ut reiciendis.","created_at":"2015-03-25T09:02:55.875Z"},{"id":6,"name":"Sed fuga quo consequatur omnis voluptas nam.","created_at":"2015-03-25T09:02:56.093Z"},{"id":9,"name":"Iste sapiente deserunt hic nobis.","created_at":"2015-03-25T09:02:56.436Z"},{"id":11,"name":"Eveniet similique autem eligendi saepe praesentium voluptate molestiae distinctio.","created_at":"2015-03-25T09:02:56.654Z"},{"id":15,"name":"A labore ex incidunt.","created_at":"2015-03-25T09:02:57.066Z"},{"id":24,"name":"Quia quas nihil voluptas dolor et incidunt error ullam.","created_at":"2015-03-25T09:02:58.137Z"}]}[~/bloc/students/umar-khokhar/projects/blocitoff-api (get-users * u=)]
```

Could you use [that list of HTTP headers](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields) to get a feeling for all the headers above?

The first part of the output is your HTTP request, with a few headers:

``` sh
> GET /api/users/6/items HTTP/1.1 # This, is not a header, it displays the HTTP verb and target
> User-Agent: curl/7.35.0 # The HTTP request header's list starts here
> Host: localhost:3000
> Accept: */*
```

The second part is the HTTP response; it has more headers:

``` sh
< HTTP/1.1 200 OK # This, is not a header, it displays the request's protocol and status
< X-Frame-Options: SAMEORIGIN # The response headers' list starts here
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Type: application/json; charset=utf-8
< Etag: W/"046556ec03b7df39639c042b75c9d03c"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: d8d4d5ab-822e-4e7a-9910-c57747a9bc11
< X-Runtime: 0.010191
* Server WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26) is not blacklisted
< Server: WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26)
< Date: Wed, 25 Mar 2015 09:04:54 GMT
< Content-Length: 735
< Connection: Keep-Alive
```

**Comment by chikamichi** [comment]
Don't hesitate to tick checkboxes and mark this as completed.
