### ISSUE TITLE
user#show not displaying items as json

### ISSUE THREAD

**Issue by UJKhokhar** [UJKhokhar/blocitoff-api#4]
A users items are not embedded within the user serialized object. I might have misread the documentation, but the embedded section says that it should be default if the associations are declared in the serializers. 

Any ideas?

**Comment by chikamichi** [comment]
Sorry for the delay.

I reproduce that bug. Currently troubleshooting, not sure what might be wrong there.

**Comment by chikamichi** [comment]
I've found what is wrong. Basically, [version 0.9.x of active_model_serializers doesn't work with Rails 4.2.x](https://github.com/rails-api/active_model_serializers/issues/641), so you need to use the latest version available on the master branch (which will eventually become 0.10.0). The maintainer said in a commit that they're using the code from their master branch in production without any issue. I'd say it's ok for your project ;) Could be annoying in "real life", though.

To start using the master branch, edit your Gemfile so it contains:

``` ruby
gem "active_model_serializers", github: "rails-api/active_model_serializers", branch: "master"
```

And then run `bundle update active_model_serializers`. Restart your server and you should be good to go.

**Comment by chikamichi** [comment]
You might want to close this.
